name: Lint and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 6s
          --health-timeout 6s
          --health-retries 3
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Run build script
        run: |
          python -m venv .venv
          source .venv/bin/activate
          ./build.sh

      - name: Run linters
        run: |
          python -m venv .venv
          source .venv/bin/activate
          ruff check .

      - name: Run tests
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == '*'
        env:
          DJANGO_SETTINGS_MODULE: task_manager.settings
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/postgres'
          SECRET_KEY: open
        with:
          coverageCommand: | 
            python -m venv .venv
            source .venv/bin/activate
            python manage.py test
          debug: true
