name: test and linter check
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 011235!
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and run linter
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          uv pip install .
          uv pip install ruff
          uv pip install coverage
          ruff check .
      - name: Run tests with coverage
        run: |
          make coverage
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'pp'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          DATABASE_URL: 'postgresql://postgres:011235!@127.0.0.1:5432/postgres'
          SECRET_KEY: not_so_secret
        with:
          coverageCommand: make coverage
          debug: true
